{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qualys-cloud-agent.serviceAccountName" . }}
  namespace: {{ include "qualys-cloud-agent.namespace" . }}
  labels:
    {{- include "qualys-cloud-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "qualys-cloud-agent.fullname" . }}
  labels:
    {{- include "qualys-cloud-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "qualys-cloud-agent.fullname" . }}
  labels:
    {{- include "qualys-cloud-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "qualys-cloud-agent.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "qualys-cloud-agent.serviceAccountName" . }}
  namespace: {{ include "qualys-cloud-agent.namespace" . }}
{{- end }}
